### ISSUE TITLE
Infer terlalu lama di model non colab.

### ISSUE THREAD

**Issue by mocci24** [ArkanDash/Multi-Model-RVC-Inference#3]
![image](https://github.com/ArkanDash/Multi-Model-RVC-Inference/assets/133739663/00398c67-7681-4e66-8ebb-244268c2f3f9)
di lognya terlihat "converting" tapi dalam banayk model secara bersamaan, normal gk nih mas?

**Comment by mocci24** [comment]
durasi file 1 menit pas, apa masih terlalu panjang?
mode 'rmvpe'

**Comment by ArkanDash** [comment]
Ya itu dipake banyak orang jadinya keluar lognya.
Tapi queue/ngantrinya 1 1 itu
contohnya di kode multi model ini concurrency countnya ku set 1 biar kalo pake harus ngantri 1 1 kalo mau di ubah bisa diganti di paling bawah kode app.py concurrency countnya set bebas.
Di rvc genshin impact ku set 5
max sizenya itu max queue, jadinya maximal 50 queue kalo lebih dari itu harus nunggu queuenya berkurang
